name: Packer Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  branch:
    name: Get branch name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: branch-check
        run: |
          echo "Running on branch ${{ github.ref }}"
          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
            echo "env_name=production" >> $GITHUB_OUTPUT
          else
             echo "env_name=sandbox" >> $GITHUB_OUTPUT
          fi
    outputs:
      env_name: ${{ steps.branch-check.outputs.env_name }}
  run-test:
    needs: [branch]
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_PAT }}
          event-type: run-test
          client-payload: '{"environment": "${{ needs.branch.outputs.env_name }}"}'
  packer:
    name: Packer Build
    needs: [run-test]
    runs-on: ubuntu-latest
    environment: ${{ needs.branch.outputs.env_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Branch check
        id: branch-check
        run: |
          echo "Running on branch ${{ github.ref }}"
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            echo "env_name=production" >> $GITHUB_OUTPUT
          else
             echo "env_name=sandbox" >> $GITHUB_OUTPUT
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        with:
          version: '1.8.6'

      - name: Packer Init
        run: |
          packer init packer

      - name: Build Image
        run: |
          packer build packer