name: Check and Increment Version on Merge

on:
  pull_request:
    types:
      - synchronize


jobs:
  print-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print version
        run: |
          echo ${{ github.event.pull_request.base.ref }}
          if [[ ${{ github.event.pull_request.base.ref }} == "master" ]]; then
            git fetch --unshallow --tags
            git describe --abbrev=0 --tags
          elif [[ ${{ github.event.pull_request.base.ref }} =~ ^release\/v[0-9]+\.[0-9]+$ ]]; then
            git fetch --tags
            git describe --abbrev=0 --tags ${{ steps.get-branch.outputs.branch }}
          fi