name: Check Patch Version Compatibility

on:
  pull_request:
    types: [opened, reopened]

jobs:
  check-semver-on-non-master:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.ref != 'refs/heads/master' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check PR for Semantic Version
        run: |
          PR_TITLE=$(jq -r '.pull_request.title' $GITHUB_EVENT_PATH)
          PR_BODY=$(jq -r '.pull_request.body' $GITHUB_EVENT_PATH)
          SEMVER_REGEX="\+semver:(major|minor|patch|pre|build)"
          if ! ([[ "$PR_TITLE" =~ $SEMVER_REGEX ]] || [[ "$PR_BODY" =~ $SEMVER_REGEX ]]); then
            echo "This PR does not contain a semantic version string."
            exit 1
          fi